# spring:
#   jpa:
#     properties:
#       jakarta:
#         persistence:
#           schema-generation:
#             create-source: metadata
#             scripts:
#               action: create
#               create-target: create.sql
#       hibernate:
#         hbm2ddl:
#           delimiter: ;

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: postgres
    password: 1234567

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
